[package]
name = "craking_coding_interview"
version = "0.1.0"
authors = ["Sandip Dey <sandip.dey1988@yahoo.com>"]
edition = "2021"

[dependencies]
rand = "0.8.5"
assert_approx_eq = "1.1.0"
paste = "1.0.3"
pretty_assertions = "1.3.0"
threadpool = "1.8.1"
bit-vec= "0.6.3"
num = "0.4"